### ISSUE TITLE
Request for unpublish this website

### ISSUE THREAD

**Issue by rodrigok** [Rodriq/GSoC-2019-Interactive-APIs-Docs#48]
Hi @Rodriq I'm Rodrigo Nascimento, CTO at Rocket.Chat.

Sorry for bothering you, but can you remove the public page of this repo that is linked by https://rodriq.github.io/GSoC-2019-Interactive-APIs-Docs/developer-guides/schema-definition/?

It's really outdated and some users are getting there since it's indexed by google, we would appreciate if you can unpublish it.

Thank you

**Comment by Rodriq** [comment]
> Hi @Rodriq I'm Rodrigo Nascimento, CTO at Rocket.Chat.
> 
> Sorry for bothering you, but can you remove the public page of this repo that is linked by https://rodriq.github.io/GSoC-2019-Interactive-APIs-Docs/developer-guides/schema-definition/?
> 
> It's really outdated and some users are getting there since it's indexed by google, we would appreciate if you can unpublish it.
> 
> Thank you

Okay sure!
  But I guess the repo can stay right?

**Comment by rodrigok** [comment]
@Rodriq sure, feel free to keep the repo.

Thank you so much.
